import 'dart:io';

import 'package:flutter/material.dart';

import '../../services/find_doctor.dart';
import '../Chat/chatScreen.dart';
import '../Guide/skinGuideScreen.dart';
import '../Reports/reportSummarySheet.dart';
import '../Share/share_with_doctor.dart';
import '../app_data.dart';
import '../theme.dart';
import '../widgets/app_logo_mark.dart';
import '../widgets/markdown_text.dart';
import '../widgets/video_background.dart';

/// Screening result screen.
///
/// Renders the `POST /predict` response from the Scan4Disease backend. It is
/// careful to honour the response contract exactly:
///   * `probabilities` is a LIST of {code, name, probability, malignancy}
///   * `triage` is an OBJECT {category, label, advice, reasons, low_confidence}
///   * `confidence` is a model score, never presented as a disease probability
///   * the Grad-CAM overlay is fetched from an absolute URL the API client set
///   * the fixed disclaimer comes from the backend (falls back to a local copy)
class DiagnosisResultsUI extends StatelessWidget {
  const DiagnosisResultsUI({super.key, required this.diagnosisData, this.report});
  final Map<String, dynamic> diagnosisData;

  /// The saved screening this result belongs to, when opened straight after a scan. Present
  /// (with an id and a device-local image) it enables the "share with a doctor" card; null
  /// (e.g. viewing an old report from history whose local image is gone) hides it.
  final ScreeningReport? report;

  bool get _canShare => report?.id != null && (report?.imagePath ?? '').isNotEmpty;

  static const String _fallbackDisclaimer =
      'IMPORTANT\n\nThis result is generated by an AI screening system and is not a '
      'medical diagnosis. Please consult a qualified dermatologist for professional '
      'evaluation, especially if the lesion is new, changing, painful, bleeding, or '
      'otherwise concerning.';

  @override
  Widget build(BuildContext context) {
    final outcome = _string('outcome', 'lesion');
    final isLesion = outcome == 'lesion';

    final name = _string('predicted_name', _string('predicted_class', 'Screening result'));
    final code = isLesion ? _string('predicted_class', '') : '';
    final confidence = isLesion ? _double('confidence') : null;
    final stub = diagnosisData['stub'] == true;

    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.white.withValues(alpha: 0.85),
        elevation: 0,
        scrolledUnderElevation: 1,
        title: const Text('Screening result'),
        actions: [
          if (report != null)
            IconButton(
              tooltip: 'Doctor summary',
              icon: const Icon(Icons.summarize_outlined),
              onPressed: () => showReportSummarySheet(context, report!),
            ),
        ],
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          const VideoBackground.ambient(),
          SafeArea(
            child: ListView(
              padding: const EdgeInsets.fromLTRB(18, 12, 18, 32),
              children: [
                if (stub) _stubBanner(),
                _headline(name, code, confidence),
                const SizedBox(height: 16),
                // The screened photograph itself. Also the Hero landing point
                // for the thumbnail on the Reports list.
                _lesionCard(),
                _triageCard(),
                const SizedBox(height: 14),
                // Send this screening to a verified doctor for review (patient-initiated sharing).
                if (_canShare) ...[
                  _shareCard(context),
                  const SizedBox(height: 14),
                ],
                // Talk to the assistant about this specific result (diagnosis-aware chat).
                _askCard(context),
                const SizedBox(height: 14),
                // Shown after every screening (lesion, healthy, or wound) so the user always has
                // a clear route to professional in-person care.
                FindDoctorCard(subtitle: _doctorSubtitle(outcome)),
                const SizedBox(height: 14),
                _gradcamCard(),
                if (isLesion) _explanationCard(),
                _probabilitiesCard(),
                const SizedBox(height: 14),
                // Explains this specific result in plain language, and opens the full guide.
                UnderstandResultBar(
                  confidence: confidence,
                  triage: diagnosisData['triage'] is Map ? diagnosisData['triage'] as Map : null,
                  hasHeatmap: (diagnosisData['gradcam_display_url']?.toString() ?? '').isNotEmpty,
                  isLesion: isLesion,
                ),
                const SizedBox(height: 14),
                _disclaimerCard(),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // --- share-with-a-doctor CTA -----------------------------------------------

  Widget _shareCard(BuildContext context) => Card(
        clipBehavior: Clip.antiAlias,
        child: InkWell(
          onTap: () => showShareWithDoctorSheet(
            context,
            report!,
            gradcamUrl: diagnosisData['gradcam_display_url']?.toString(),
          ),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Row(children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: Themes.brandTint.withValues(alpha: 0.70),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.white.withValues(alpha: 0.85)),
                ),
                child: const Icon(Icons.medical_services_outlined, color: Themes.brand, size: 22),
              ),
              const SizedBox(width: 14),
              const Expanded(
                child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Text('Share with a verified doctor',
                      style: TextStyle(color: Themes.ink, fontWeight: FontWeight.w800, fontSize: 15)),
                  SizedBox(height: 3),
                  Text('Send this screening and image to a dermatologist for clinical review.',
                      style: TextStyle(color: Themes.inkSoft, height: 1.35, fontSize: 12.5)),
                ]),
              ),
              const Icon(Icons.chevron_right_rounded, color: Themes.brand),
            ]),
          ),
        ),
      );

  // --- ask-the-assistant CTA -------------------------------------------------

  Widget _askCard(BuildContext context) => Card(
        clipBehavior: Clip.antiAlias,
        child: InkWell(
          onTap: () => _openChat(context),
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Row(children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: Themes.brandTint.withValues(alpha: 0.70),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.white.withValues(alpha: 0.85)),
                ),
                child: const Icon(Icons.forum_outlined, color: Themes.brand, size: 22),
              ),
              const SizedBox(width: 14),
              Expanded(
                child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  Wrap(
                    crossAxisAlignment: WrapCrossAlignment.center,
                    spacing: 8,
                    runSpacing: 4,
                    children: [
                      const Text('Ask about this result',
                          style: TextStyle(fontWeight: FontWeight.w800, fontSize: 15, color: Themes.ink)),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
                        decoration: BoxDecoration(
                          color: Themes.brandTint.withValues(alpha: 0.75),
                          borderRadius: const BorderRadius.all(Radius.circular(6)),
                          border: Border.all(color: Colors.white.withValues(alpha: 0.85)),
                        ),
                        child: const Text('AI Assistant',
                            style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: Themes.brand)),
                      ),
                    ],
                  ),
                  const SizedBox(height: 3),
                  const Text('Chat with the assistant to understand what it means and recommended next steps.',
                      style: TextStyle(color: Themes.inkSoft, height: 1.35, fontSize: 12.5)),
                ]),
              ),
              const Icon(Icons.chevron_right_rounded, color: Themes.brand),
            ]),
          ),
        ),
      );

  void _openChat(BuildContext context) {
    final triage = diagnosisData['triage'];
    final prediction = <String, dynamic>{
      'predicted_class': _string('predicted_class', ''),
      'confidence': _double('confidence') ?? 0.0,
      'triage_category': (triage is Map ? triage['category']?.toString() : '') ?? '',
      'low_confidence': triage is Map && triage['low_confidence'] == true,
      if (_string('gradcam_focus', '').isNotEmpty) 'gradcam_focus': _string('gradcam_focus', ''),
    };
    final q = diagnosisData['questionnaire'];
    final questionnaire = q is Map ? Map<String, dynamic>.from(q) : null;
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ChatScreen(
          prediction: prediction,
          questionnaire: questionnaire,
          conditionName: _string('predicted_name', ''),
        ),
      ),
    );
  }

  String _doctorSubtitle(String outcome) => switch (outcome) {
        'healthy' =>
          'Nothing concerning was found here, but a dermatologist can examine your skin in person.',
        'other_damage' =>
          'See a doctor if the wound does not heal, or becomes painful, swollen, or infected.',
        _ => 'Have this professionally examined by a dermatologist near you.',
      };

  // --- header with the model score ------------------------------------------

  Widget _headline(String name, String code, double? confidence) => Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Themes.brand, Themes.brandDark],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(22),
          border: Border.all(color: Colors.white.withValues(alpha: 0.35), width: 1.2),
          boxShadow: [
            BoxShadow(
              color: Themes.brand.withValues(alpha: 0.30),
              blurRadius: 22,
              offset: const Offset(0, 8),
            ),
            BoxShadow(
              color: Colors.white.withValues(alpha: 0.20),
              blurRadius: 4,
              spreadRadius: 0.5,
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Uniform brandmark (white variant to sit on the coloured banner)
            // + assessment label — replaces the "S4D MODEL ASSESSMENT" text pill.
            Row(children: [
              const AppLogoMark(size: 22, color: Colors.white, holeColor: Colors.transparent, glow: false),
              const SizedBox(width: 8),
              const Text('MODEL ASSESSMENT', style: TextStyle(color: Colors.white, fontSize: 10.5, fontWeight: FontWeight.w700, letterSpacing: 0.5)),
            ]),
            const SizedBox(height: 12),
            Text(name,
                style: const TextStyle(color: Colors.white, fontSize: 25, fontWeight: FontWeight.w800, letterSpacing: -0.01)),
            if (code.isNotEmpty)
              Padding(
                padding: const EdgeInsets.only(top: 2),
                child: Text('Model class code: ${code.toUpperCase()}',
                    style: const TextStyle(color: Colors.white70, fontSize: 12, letterSpacing: 0.8)),
              ),
            if (confidence != null) ...[
              const SizedBox(height: 16),
              ClipRRect(
                borderRadius: BorderRadius.circular(6),
                child: LinearProgressIndicator(
                  value: confidence.clamp(0, 1),
                  minHeight: 8,
                  backgroundColor: Colors.white24,
                  color: Colors.white,
                ),
              ),
              const SizedBox(height: 8),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text('Match score', style: TextStyle(color: Colors.white70, fontSize: 12.5)),
                  Text('${(confidence * 100).toStringAsFixed(1)}%',
                      style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w800, fontSize: 14)),
                ],
              ),
              const SizedBox(height: 2),
              const Text(
                'A match score — not the probability that you have this condition.',
                style: TextStyle(color: Colors.white70, fontSize: 11.5, height: 1.3),
              ),
            ],
          ],
        ),
      );

  // --- triage (colour-coded by urgency) -------------------------------------

  Widget _triageCard() {
    final triage = diagnosisData['triage'];
    if (triage is! Map) return const SizedBox.shrink();

    final category = triage['category']?.toString() ?? '';
    final label = triage['label']?.toString() ?? 'Professional review recommended';
    final advice = triage['advice']?.toString() ?? '';
    final reasons = (triage['reasons'] is List) ? List.from(triage['reasons']) : const [];
    final lowConfidence = triage['low_confidence'] == true;

    final (color, bg, border, icon) = switch (category) {
      'urgent_evaluation' => (Themes.urgent, Themes.urgentBg, Themes.urgentBorder, Icons.priority_high_rounded),
      'prompt_consultation' => (Themes.soon, Themes.soonBg, Themes.soonBorder, Icons.schedule_rounded),
      _ => (Themes.routine, Themes.routineBg, Themes.routineBorder, Icons.check_circle_outline_rounded),
    };

    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            bg.withValues(alpha: 0.85),
            bg.withValues(alpha: 0.65),
          ],
        ),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: Colors.white.withValues(alpha: 0.85), width: 1.2),
        boxShadow: [
          BoxShadow(
            color: Colors.white.withValues(alpha: 0.50),
            blurRadius: 3,
            spreadRadius: 0.5,
          ),
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.06),
            blurRadius: 18,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.15),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, color: color, size: 18),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Text(label,
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: color)),
            ),
          ]),
          if (advice.isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(advice, style: const TextStyle(height: 1.4, color: Themes.ink, fontSize: 13.5)),
          ],
          if (lowConfidence) ...[
            const SizedBox(height: 10),
            Row(crossAxisAlignment: CrossAxisAlignment.start, children: const [
              Icon(Icons.info_outline, size: 16, color: Themes.inkSoft),
              SizedBox(width: 6),
              Expanded(child: Text(
                'The model was not confident about this image — rely on a professional examination.',
                style: TextStyle(fontSize: 12.5, color: Themes.inkSoft),
              )),
            ]),
          ],
          if (reasons.isNotEmpty) ...[
            const SizedBox(height: 12),
            const Text('Clinical criteria evaluated:', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: Themes.ink)),
            const SizedBox(height: 6),
            ...reasons.map((r) => Padding(
                  padding: const EdgeInsets.only(bottom: 4),
                  child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    const Text('•  ', style: TextStyle(color: Themes.inkSoft)),
                    Expanded(child: Text(r.toString(), style: const TextStyle(height: 1.35, fontSize: 13, color: Themes.ink))),
                  ]),
                )),
          ],
        ],
      ),
    );
  }

  // --- screened photograph ---------------------------------------------------

  /// The lesion photo this result was produced from, when the device-local file
  /// is still present. Doubles as the Hero destination for the thumbnail on the
  /// Reports list, so opening a saved report flies the photo up into place
  /// instead of cutting to a new screen.
  ///
  /// Returns an empty box when there is no local file (an older report whose
  /// image has been cleared, or a result opened straight from a scan before the
  /// report is saved) — the Hero on the list side is likewise suppressed there,
  /// so the tags always pair up.
  Widget _lesionCard() {
    final path = report?.imagePath ?? '';
    if (path.isEmpty) return const SizedBox.shrink();
    final file = File(path);
    if (!file.existsSync()) return const SizedBox.shrink();

    final image = ClipRRect(
      borderRadius: BorderRadius.circular(14),
      child: Image.file(
        file,
        height: 220,
        width: double.infinity,
        fit: BoxFit.cover,
        errorBuilder: (_, __, ___) => const SizedBox.shrink(),
      ),
    );

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section(
        'Screened photograph',
        report?.id == null
            ? image
            // Matches `_lesionThumb` in reportScreen.dart. Keep the tags in sync.
            : Hero(tag: 'lesion-${report!.id}', child: image),
      ),
    );
  }

  // --- Grad-CAM overlay ------------------------------------------------------

  Widget _gradcamCard() {
    final url = diagnosisData['gradcam_display_url']?.toString();
    if (url == null || url.isEmpty) return const SizedBox.shrink();
    final focus = _string('gradcam_focus', '');

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section(
        'Model visual attention (Grad-CAM)',
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: Image.network(
                url,
                height: 220,
                width: double.infinity,
                fit: BoxFit.cover,
                loadingBuilder: (c, child, progress) => progress == null
                    ? child
                    : const SizedBox(height: 220, child: Center(child: CircularProgressIndicator())),
                // Fade the heatmap in once the bytes have arrived instead of a
                // hard cut. `frameBuilder` fires with `wasSynchronouslyLoaded`
                // true for cached images — skip the animation in that case so
                // it doesn't dip on rebuilds.
                frameBuilder: (_, child, frame, wasSync) {
                  if (wasSync) return child;
                  return AnimatedOpacity(
                    opacity: frame == null ? 0 : 1,
                    duration: const Duration(milliseconds: 260),
                    curve: Curves.easeOutCubic,
                    child: child,
                  );
                },
                errorBuilder: (c, e, s) => const SizedBox(
                  height: 100,
                  child: Center(child: Text('Heatmap unavailable (temporary asset expired).', style: TextStyle(color: Themes.inkSoft, fontSize: 12))),
                ),
              ),
            ),
            if (focus.isNotEmpty) ...[
              const SizedBox(height: 8),
              Text('Attention concentrated: $focus.',
                  style: const TextStyle(color: Themes.inkSoft, fontSize: 12.5)),
            ],
            const SizedBox(height: 4),
            const Text(
              'Highlighted regions influenced the model output. This is an explainability aid, not proof of clinical reasoning.',
              style: TextStyle(color: Themes.inkSoft, fontSize: 11.5, height: 1.3),
            ),
          ],
        ),
      ),
    );
  }

  // --- explanation -----------------------------------------------------------

  Widget _explanationCard() {
    final available = diagnosisData['explanation_available'] == true;
    final explanation = _string(
      'explanation',
      available ? '' : 'The written explanation service is offline. The result above is unaffected.',
    );
    if (explanation.isEmpty) return const SizedBox.shrink();
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section('Clinical explanation', MarkdownText(explanation, color: Themes.ink)),
    );
  }

  // --- per-class scores (LIST from the backend) ------------------------------

  Widget _probabilitiesCard() {
    final probs = diagnosisData['probabilities'];
    if (probs is! List || probs.isEmpty) return const SizedBox.shrink();

    return _section(
      'All category match scores',
      Column(
        children: [
          for (final p in probs)
            if (p is Map) _probRow(p),
        ],
      ),
    );
  }

  Widget _probRow(Map p) {
    final name = p['name']?.toString() ?? p['code']?.toString() ?? '—';
    final value = p['probability'] is num ? (p['probability'] as num).toDouble() : 0.0;
    final malignancy = p['malignancy']?.toString() ?? 'benign';
    final color = switch (malignancy) {
      'malignant' => Themes.urgent,
      'premalignant' => Themes.soon,
      _ => Themes.routine,
    };

    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Column(
        children: [
          Row(children: [
            Expanded(child: Text(name, style: const TextStyle(fontSize: 13.5, color: Themes.ink, fontWeight: FontWeight.w600))),
            Text('${(value * 100).toStringAsFixed(1)}%', style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: Themes.ink)),
          ]),
          const SizedBox(height: 5),
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value: value.clamp(0, 1),
              minHeight: 6,
              backgroundColor: Themes.border,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  // --- disclaimer + stub -----------------------------------------------------

  Widget _disclaimerCard() {
    final text = _string('disclaimer', _fallbackDisclaimer);
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Themes.warningTint,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Themes.soonBorder),
      ),
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const Icon(Icons.shield_outlined, color: Themes.warning, size: 20),
        const SizedBox(width: 10),
        Expanded(child: Text(text, style: const TextStyle(height: 1.4, color: Themes.ink, fontSize: 12.5))),
      ]),
    );
  }

  Widget _stubBanner() => Container(
        margin: const EdgeInsets.only(bottom: 14),
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Themes.danger.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: Themes.danger.withValues(alpha: 0.4)),
        ),
        child: const Row(children: [
          Icon(Icons.science_outlined, color: Themes.danger),
          SizedBox(width: 10),
          Expanded(child: Text(
            'Demo/stub mode: these values are placeholders, not a real model prediction.',
            style: TextStyle(color: Themes.danger, fontWeight: FontWeight.w600),
          )),
        ]),
      );

  // --- helpers ---------------------------------------------------------------

  Widget _section(String title, Widget child) => Card(
        child: Padding(
          padding: const EdgeInsets.all(17),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(title, style: const TextStyle(fontSize: 17, fontWeight: FontWeight.w800)),
              const SizedBox(height: 12),
              child,
            ],
          ),
        ),
      );

  String _string(String key, String fallback) {
    final v = diagnosisData[key];
    return (v == null || v.toString().isEmpty) ? fallback : v.toString();
  }

  double? _double(String key) {
    final v = diagnosisData[key];
    if (v is num) return v.toDouble();
    return double.tryParse(v?.toString() ?? '');
  }
}

/// "Understand this result" — an expandable bar at the foot of every screening result.
///
/// Explains, for *this* result, what the model score means, what the triage band is asking
/// of the user, how to read the heatmap, and what to do next. Links through to the full
/// skin health guide with its results section already open.
class UnderstandResultBar extends StatelessWidget {
  const UnderstandResultBar({
    super.key,
    required this.confidence,
    required this.triage,
    required this.hasHeatmap,
    required this.isLesion,
  });

  final double? confidence;
  final Map? triage;
  final bool hasHeatmap;
  final bool isLesion;

  String get _category => triage?['category']?.toString() ?? '';
  bool get _lowConfidence => triage?['low_confidence'] == true;

  @override
  Widget build(BuildContext context) => Card(
        clipBehavior: Clip.antiAlias,
        child: Theme(
          data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
          child: ExpansionTile(
            tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
            childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            expandedCrossAxisAlignment: CrossAxisAlignment.start,
            leading: Container(
              padding: const EdgeInsets.all(9),
              decoration: BoxDecoration(
                color: Themes.primary.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(Icons.school_outlined, color: Themes.primary),
            ),
            title: const Text('Understand this result',
                style: TextStyle(fontWeight: FontWeight.w800, fontSize: 16)),
            subtitle: const Padding(
              padding: EdgeInsets.only(top: 2),
              child: Text('What the score and triage actually mean for you.',
                  style: TextStyle(color: Themes.muted, fontSize: 12.5, height: 1.3)),
            ),
            children: [
              if (confidence != null)
                _point(
                  Icons.percent_rounded,
                  'The ${(confidence! * 100).toStringAsFixed(1)}% is a match score, not a diagnosis',
                  'It means the image resembled this category more than the others the model '
                      'knows. It is not the chance that you have this condition, and the model '
                      'can only pick from the classes it was trained on.',
                ),
              if (_category.isNotEmpty) _point(Icons.flag_outlined, _triageTitle(), _triageBody()),
              if (_lowConfidence)
                _point(
                  Icons.help_outline_rounded,
                  'Confidence was low — treat this as "unclear"',
                  'Blur, poor lighting, hair or an unfamiliar lesion all reduce confidence. '
                      'A low-confidence result is not a clean bill of health: retake the photo '
                      'in better light, or have it examined.',
                ),
              if (hasHeatmap)
                _point(
                  Icons.blur_on_rounded,
                  'Read the heatmap as attention, not proof',
                  'Warm colours mark what influenced the output. Heat centred on the lesion is '
                      'reassuring; heat on background skin or hair means the model may have '
                      'keyed on an artefact, so weigh the result accordingly.',
                ),
              _point(
                Icons.check_circle_outline_rounded,
                'What to do next',
                isLesion
                    ? 'Photograph the same spot monthly so change is easy to see, and book a '
                        'dermatologist if it grows, changes colour, bleeds or itches — '
                        'regardless of what this screen said.'
                    : 'Keep an eye on the area and seek care if it worsens, fails to heal, or '
                        'becomes painful, swollen or infected.',
              ),
              const SizedBox(height: 4),
              SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (_) => const SkinGuideScreen(focusResults: true)),
                  ),
                  icon: const Icon(Icons.menu_book_outlined, size: 18),
                  label: const Text('Open the full skin health guide'),
                ),
              ),
            ],
          ),
        ),
      );

  String _triageTitle() => switch (_category) {
        'urgent_evaluation' => 'Urgent evaluation — act on this within days',
        'prompt_consultation' => 'Prompt consultation — book an appointment soon',
        _ => 'Routine monitoring — keep watching this spot',
      };

  String _triageBody() => switch (_category) {
        'urgent_evaluation' =>
          'The triage band is the part to act on. It is set cautiously and can be more urgent '
              'than the top prediction alone suggests — that is deliberate, because missing a '
              'serious lesion is far costlier than an unnecessary visit.',
        'prompt_consultation' =>
          'Arrange a professional look in the next few weeks. This band means the findings '
              'are not clearly benign, not that something is definitely wrong.',
        _ =>
          'Nothing here demanded urgent action, but screening cannot rule anything out. '
              'Re-check monthly and escalate on any change.',
      };

  Widget _point(IconData icon, String title, String body) => Padding(
        padding: const EdgeInsets.only(bottom: 14),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Padding(
              padding: const EdgeInsets.only(top: 2),
              child: Icon(icon, size: 17, color: Themes.primary),
            ),
            const SizedBox(width: 9),
            Expanded(
              child: Text(title,
                  style: const TextStyle(fontWeight: FontWeight.w800, height: 1.3)),
            ),
          ]),
          const SizedBox(height: 4),
          Padding(
            padding: const EdgeInsets.only(left: 26),
            child: Text(body,
                style: const TextStyle(color: Themes.muted, height: 1.45, fontSize: 12.8)),
          ),
        ]),
      );
}
