import 'package:flutter/material.dart';

import '../../services/find_doctor.dart';
import '../Chat/chatScreen.dart';
import '../Guide/skinGuideScreen.dart';
import '../theme.dart';
import '../widgets/markdown_text.dart';

/// Screening result screen.
///
/// Renders the `POST /predict` response from the Scan4Disease backend. It is
/// careful to honour the response contract exactly:
///   * `probabilities` is a LIST of {code, name, probability, malignancy}
///   * `triage` is an OBJECT {category, label, advice, reasons, low_confidence}
///   * `confidence` is a model score, never presented as a disease probability
///   * the Grad-CAM overlay is fetched from an absolute URL the API client set
///   * the fixed disclaimer comes from the backend (falls back to a local copy)
class DiagnosisResultsUI extends StatelessWidget {
  const DiagnosisResultsUI({super.key, required this.diagnosisData});
  final Map<String, dynamic> diagnosisData;

  static const String _fallbackDisclaimer =
      'IMPORTANT\n\nThis result is generated by an AI screening system and is not a '
      'medical diagnosis. Please consult a qualified dermatologist for professional '
      'evaluation, especially if the lesion is new, changing, painful, bleeding, or '
      'otherwise concerning.';

  @override
  Widget build(BuildContext context) {
    // The front-stage router can return a non-disease outcome. For 'healthy' and
    // 'other_damage' there is no disease class, no per-class score, and no Grad-CAM, so the
    // disease-specific chrome (class code, model-score bar, LLM explanation) is suppressed
    // and only the name + safe guidance + disclaimer are shown.
    final outcome = _string('outcome', 'lesion');
    final isLesion = outcome == 'lesion';

    final name = _string('predicted_name', _string('predicted_class', 'Screening result'));
    final code = isLesion ? _string('predicted_class', '') : '';
    final confidence = isLesion ? _double('confidence') : null;
    final stub = diagnosisData['stub'] == true;

    return Scaffold(
      appBar: AppBar(title: const Text('Screening result')),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(18, 8, 18, 32),
        children: [
          if (stub) _stubBanner(),
          _headline(name, code, confidence),
          const SizedBox(height: 16),
          _triageCard(),
          const SizedBox(height: 14),
          // Talk to the assistant about this specific result (diagnosis-aware chat).
          _askCard(context),
          const SizedBox(height: 14),
          // Shown after every screening (lesion, healthy, or wound) so the user always has
          // a clear route to professional in-person care.
          FindDoctorCard(subtitle: _doctorSubtitle(outcome)),
          const SizedBox(height: 14),
          _gradcamCard(),
          if (isLesion) _explanationCard(),
          _probabilitiesCard(),
          const SizedBox(height: 14),
          // Explains this specific result in plain language, and opens the full guide.
          UnderstandResultBar(
            confidence: confidence,
            triage: diagnosisData['triage'] is Map ? diagnosisData['triage'] as Map : null,
            hasHeatmap: (diagnosisData['gradcam_display_url']?.toString() ?? '').isNotEmpty,
            isLesion: isLesion,
          ),
          const SizedBox(height: 14),
          _disclaimerCard(),
        ],
      ),
    );
  }

  // --- ask-the-assistant CTA -------------------------------------------------

  Widget _askCard(BuildContext context) => Container(
        decoration: BoxDecoration(
          color: Themes.primary.withValues(alpha: 0.07),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: Themes.primary.withValues(alpha: 0.35)),
        ),
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            borderRadius: BorderRadius.circular(20),
            onTap: () => _openChat(context),
            child: Padding(
              padding: const EdgeInsets.all(18),
              child: Row(children: [
                Container(
                  padding: const EdgeInsets.all(11),
                  decoration: BoxDecoration(
                    color: Themes.primary.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(14),
                  ),
                  child: const Icon(Icons.forum_outlined, color: Themes.primary),
                ),
                const SizedBox(width: 14),
                const Expanded(
                  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text('Ask about this result',
                        style: TextStyle(fontWeight: FontWeight.w800, fontSize: 16)),
                    SizedBox(height: 3),
                    Text('Chat with the assistant to understand what it means and what to do.',
                        style: TextStyle(color: Themes.muted, height: 1.35, fontSize: 13)),
                  ]),
                ),
                const Icon(Icons.chevron_right_rounded, color: Themes.primary),
              ]),
            ),
          ),
        ),
      );

  void _openChat(BuildContext context) {
    final triage = diagnosisData['triage'];
    final prediction = <String, dynamic>{
      'predicted_class': _string('predicted_class', ''),
      'confidence': _double('confidence') ?? 0.0,
      'triage_category': (triage is Map ? triage['category']?.toString() : '') ?? '',
      'low_confidence': triage is Map && triage['low_confidence'] == true,
      if (_string('gradcam_focus', '').isNotEmpty) 'gradcam_focus': _string('gradcam_focus', ''),
    };
    final q = diagnosisData['questionnaire'];
    final questionnaire = q is Map ? Map<String, dynamic>.from(q) : null;
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ChatScreen(
          prediction: prediction,
          questionnaire: questionnaire,
          conditionName: _string('predicted_name', ''),
        ),
      ),
    );
  }

  String _doctorSubtitle(String outcome) => switch (outcome) {
        'healthy' =>
          'Nothing concerning was found here, but a dermatologist can examine your skin in person.',
        'other_damage' =>
          'See a doctor if the wound does not heal, or becomes painful, swollen, or infected.',
        _ => 'Have this professionally examined by a dermatologist near you.',
      };

  // --- header with the model score ------------------------------------------

  Widget _headline(String name, String code, double? confidence) => Container(
        padding: const EdgeInsets.all(22),
        decoration: BoxDecoration(
          gradient: const LinearGradient(colors: [Themes.primary, Themes.primaryDark]),
          borderRadius: BorderRadius.circular(24),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Row(children: [
              Icon(Icons.verified_outlined, color: Colors.white, size: 26),
              SizedBox(width: 8),
              Text('AI-assisted assessment', style: TextStyle(color: Colors.white70)),
            ]),
            const SizedBox(height: 14),
            Text(name,
                style: const TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.w800)),
            if (code.isNotEmpty)
              Text(code.toUpperCase(),
                  style: const TextStyle(color: Colors.white60, fontSize: 13, letterSpacing: 1.2)),
            if (confidence != null) ...[
              const SizedBox(height: 18),
              ClipRRect(
                borderRadius: BorderRadius.circular(10),
                child: LinearProgressIndicator(
                  value: confidence.clamp(0, 1),
                  minHeight: 10,
                  backgroundColor: Colors.white24,
                  color: Colors.white,
                ),
              ),
              const SizedBox(height: 8),
              Text('Model score: ${(confidence * 100).toStringAsFixed(1)}%',
                  style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700)),
              const SizedBox(height: 2),
              const Text(
                'This is how strongly the image matched this category — not the chance you have it.',
                style: TextStyle(color: Colors.white70, fontSize: 12, height: 1.3),
              ),
            ],
          ],
        ),
      );

  // --- triage (colour-coded by urgency) -------------------------------------

  Widget _triageCard() {
    final triage = diagnosisData['triage'];
    if (triage is! Map) return const SizedBox.shrink();

    final category = triage['category']?.toString() ?? '';
    final label = triage['label']?.toString() ?? 'Professional review recommended';
    final advice = triage['advice']?.toString() ?? '';
    final reasons = (triage['reasons'] is List) ? List.from(triage['reasons']) : const [];
    final lowConfidence = triage['low_confidence'] == true;

    final (color, icon) = switch (category) {
      'urgent_evaluation' => (Themes.danger, Icons.priority_high_rounded),
      'prompt_consultation' => (Themes.warning, Icons.schedule_rounded),
      _ => (Themes.mint, Icons.check_circle_outline_rounded),
    };

    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withValues(alpha: 0.4)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            Icon(icon, color: color),
            const SizedBox(width: 10),
            Expanded(
              child: Text(label,
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800, color: color)),
            ),
          ]),
          if (advice.isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(advice, style: const TextStyle(height: 1.4)),
          ],
          if (lowConfidence) ...[
            const SizedBox(height: 10),
            Row(crossAxisAlignment: CrossAxisAlignment.start, children: const [
              Icon(Icons.info_outline, size: 18, color: Themes.muted),
              SizedBox(width: 6),
              Expanded(child: Text(
                'The model was not confident about this image — rely on a professional examination.',
                style: TextStyle(fontSize: 13, color: Themes.muted),
              )),
            ]),
          ],
          if (reasons.isNotEmpty) ...[
            const SizedBox(height: 12),
            const Text('Why this recommendation', style: TextStyle(fontWeight: FontWeight.w700)),
            const SizedBox(height: 6),
            ...reasons.map((r) => Padding(
                  padding: const EdgeInsets.only(bottom: 4),
                  child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    const Text('•  '),
                    Expanded(child: Text(r.toString(), style: const TextStyle(height: 1.35))),
                  ]),
                )),
          ],
        ],
      ),
    );
  }

  // --- Grad-CAM overlay ------------------------------------------------------

  Widget _gradcamCard() {
    final url = diagnosisData['gradcam_display_url']?.toString();
    if (url == null || url.isEmpty) return const SizedBox.shrink();
    final focus = _string('gradcam_focus', '');

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section(
        'Where the model looked',
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(14),
              child: Image.network(
                url,
                height: 240,
                width: double.infinity,
                fit: BoxFit.cover,
                loadingBuilder: (c, child, progress) => progress == null
                    ? child
                    : const SizedBox(height: 240, child: Center(child: CircularProgressIndicator())),
                errorBuilder: (c, e, s) => const SizedBox(
                  height: 120,
                  child: Center(child: Text('Heatmap unavailable (it expires shortly after a scan).')),
                ),
              ),
            ),
            if (focus.isNotEmpty) ...[
              const SizedBox(height: 8),
              Text('Heat concentrated $focus.',
                  style: const TextStyle(color: Themes.muted, fontSize: 13)),
            ],
            const SizedBox(height: 4),
            const Text(
              'Warmer colours mark regions that influenced the prediction. This is an aid, not proof of medical reasoning.',
              style: TextStyle(color: Themes.muted, fontSize: 12, height: 1.3),
            ),
          ],
        ),
      ),
    );
  }

  // --- explanation -----------------------------------------------------------

  Widget _explanationCard() {
    final available = diagnosisData['explanation_available'] == true;
    final explanation = _string(
      'explanation',
      available ? '' : 'The written explanation service is offline. The result above is unaffected.',
    );
    if (explanation.isEmpty) return const SizedBox.shrink();
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section('What this means', MarkdownText(explanation, color: Themes.ink)),
    );
  }

  // --- per-class scores (LIST from the backend) ------------------------------

  Widget _probabilitiesCard() {
    final probs = diagnosisData['probabilities'];
    if (probs is! List || probs.isEmpty) return const SizedBox.shrink();

    return _section(
      'All class scores',
      Column(
        children: [
          for (final p in probs)
            if (p is Map) _probRow(p),
        ],
      ),
    );
  }

  Widget _probRow(Map p) {
    final name = p['name']?.toString() ?? p['code']?.toString() ?? '—';
    final value = p['probability'] is num ? (p['probability'] as num).toDouble() : 0.0;
    final malignancy = p['malignancy']?.toString() ?? 'benign';
    final color = switch (malignancy) {
      'malignant' => Themes.danger,
      'premalignant' => Themes.warning,
      _ => Themes.mint,
    };

    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Column(
        children: [
          Row(children: [
            Expanded(child: Text(name)),
            Text('${(value * 100).toStringAsFixed(1)}%', style: const TextStyle(fontWeight: FontWeight.w700)),
          ]),
          const SizedBox(height: 5),
          ClipRRect(
            borderRadius: BorderRadius.circular(5),
            child: LinearProgressIndicator(
              value: value.clamp(0, 1),
              minHeight: 6,
              backgroundColor: Themes.border,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  // --- disclaimer + stub -----------------------------------------------------

  Widget _disclaimerCard() {
    final text = _string('disclaimer', _fallbackDisclaimer);
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFFFF8E8),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: const Color(0xFFF1D18A)),
      ),
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        const Icon(Icons.warning_amber_rounded, color: Themes.warning),
        const SizedBox(width: 10),
        Expanded(child: Text(text, style: const TextStyle(height: 1.4))),
      ]),
    );
  }

  Widget _stubBanner() => Container(
        margin: const EdgeInsets.only(bottom: 14),
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Themes.danger.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: Themes.danger.withValues(alpha: 0.4)),
        ),
        child: const Row(children: [
          Icon(Icons.science_outlined, color: Themes.danger),
          SizedBox(width: 10),
          Expanded(child: Text(
            'Demo/stub mode: these values are placeholders, not a real model prediction.',
            style: TextStyle(color: Themes.danger, fontWeight: FontWeight.w600),
          )),
        ]),
      );

  // --- helpers ---------------------------------------------------------------

  Widget _section(String title, Widget child) => Card(
        child: Padding(
          padding: const EdgeInsets.all(17),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(title, style: const TextStyle(fontSize: 17, fontWeight: FontWeight.w800)),
              const SizedBox(height: 12),
              child,
            ],
          ),
        ),
      );

  String _string(String key, String fallback) {
    final v = diagnosisData[key];
    return (v == null || v.toString().isEmpty) ? fallback : v.toString();
  }

  double? _double(String key) {
    final v = diagnosisData[key];
    if (v is num) return v.toDouble();
    return double.tryParse(v?.toString() ?? '');
  }
}

/// "Understand this result" — an expandable bar at the foot of every screening result.
///
/// Explains, for *this* result, what the model score means, what the triage band is asking
/// of the user, how to read the heatmap, and what to do next. Links through to the full
/// skin health guide with its results section already open.
class UnderstandResultBar extends StatelessWidget {
  const UnderstandResultBar({
    super.key,
    required this.confidence,
    required this.triage,
    required this.hasHeatmap,
    required this.isLesion,
  });

  final double? confidence;
  final Map? triage;
  final bool hasHeatmap;
  final bool isLesion;

  String get _category => triage?['category']?.toString() ?? '';
  bool get _lowConfidence => triage?['low_confidence'] == true;

  @override
  Widget build(BuildContext context) => Card(
        clipBehavior: Clip.antiAlias,
        child: Theme(
          data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
          child: ExpansionTile(
            tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
            childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            expandedCrossAxisAlignment: CrossAxisAlignment.start,
            leading: Container(
              padding: const EdgeInsets.all(9),
              decoration: BoxDecoration(
                color: Themes.primary.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Icon(Icons.school_outlined, color: Themes.primary),
            ),
            title: const Text('Understand this result',
                style: TextStyle(fontWeight: FontWeight.w800, fontSize: 16)),
            subtitle: const Padding(
              padding: EdgeInsets.only(top: 2),
              child: Text('What the score and triage actually mean for you.',
                  style: TextStyle(color: Themes.muted, fontSize: 12.5, height: 1.3)),
            ),
            children: [
              if (confidence != null)
                _point(
                  Icons.percent_rounded,
                  'The ${(confidence! * 100).toStringAsFixed(1)}% is a match score, not a diagnosis',
                  'It means the image resembled this category more than the others the model '
                      'knows. It is not the chance that you have this condition, and the model '
                      'can only pick from the classes it was trained on.',
                ),
              if (_category.isNotEmpty) _point(Icons.flag_outlined, _triageTitle(), _triageBody()),
              if (_lowConfidence)
                _point(
                  Icons.help_outline_rounded,
                  'Confidence was low — treat this as "unclear"',
                  'Blur, poor lighting, hair or an unfamiliar lesion all reduce confidence. '
                      'A low-confidence result is not a clean bill of health: retake the photo '
                      'in better light, or have it examined.',
                ),
              if (hasHeatmap)
                _point(
                  Icons.blur_on_rounded,
                  'Read the heatmap as attention, not proof',
                  'Warm colours mark what influenced the output. Heat centred on the lesion is '
                      'reassuring; heat on background skin or hair means the model may have '
                      'keyed on an artefact, so weigh the result accordingly.',
                ),
              _point(
                Icons.check_circle_outline_rounded,
                'What to do next',
                isLesion
                    ? 'Photograph the same spot monthly so change is easy to see, and book a '
                        'dermatologist if it grows, changes colour, bleeds or itches — '
                        'regardless of what this screen said.'
                    : 'Keep an eye on the area and seek care if it worsens, fails to heal, or '
                        'becomes painful, swollen or infected.',
              ),
              const SizedBox(height: 4),
              SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: () => Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (_) => const SkinGuideScreen(focusResults: true)),
                  ),
                  icon: const Icon(Icons.menu_book_outlined, size: 18),
                  label: const Text('Open the full skin health guide'),
                ),
              ),
            ],
          ),
        ),
      );

  String _triageTitle() => switch (_category) {
        'urgent_evaluation' => 'Urgent evaluation — act on this within days',
        'prompt_consultation' => 'Prompt consultation — book an appointment soon',
        _ => 'Routine monitoring — keep watching this spot',
      };

  String _triageBody() => switch (_category) {
        'urgent_evaluation' =>
          'The triage band is the part to act on. It is set cautiously and can be more urgent '
              'than the top prediction alone suggests — that is deliberate, because missing a '
              'serious lesion is far costlier than an unnecessary visit.',
        'prompt_consultation' =>
          'Arrange a professional look in the next few weeks. This band means the findings '
              'are not clearly benign, not that something is definitely wrong.',
        _ =>
          'Nothing here demanded urgent action, but screening cannot rule anything out. '
              'Re-check monthly and escalate on any change.',
      };

  Widget _point(IconData icon, String title, String body) => Padding(
        padding: const EdgeInsets.only(bottom: 14),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Padding(
              padding: const EdgeInsets.only(top: 2),
              child: Icon(icon, size: 17, color: Themes.primary),
            ),
            const SizedBox(width: 9),
            Expanded(
              child: Text(title,
                  style: const TextStyle(fontWeight: FontWeight.w800, height: 1.3)),
            ),
          ]),
          const SizedBox(height: 4),
          Padding(
            padding: const EdgeInsets.only(left: 26),
            child: Text(body,
                style: const TextStyle(color: Themes.muted, height: 1.45, fontSize: 12.8)),
          ),
        ]),
      );
}
