import 'dart:io';

import 'package:flutter/material.dart';

import '../../services/find_doctor.dart';
import '../../services/language_service.dart';
import '../../services/theme_service.dart';
import '../Chat/chatScreen.dart';
import '../Guide/skinGuideScreen.dart';
import '../Reports/reportSummarySheet.dart';
import '../Share/share_with_doctor.dart';
import '../app_data.dart';
import '../theme.dart';
import '../widgets/app_logo_mark.dart';
import '../widgets/markdown_text.dart';
import '../widgets/video_background.dart';

/// Screening result screen.
///
/// Renders the `POST /predict` response from the Scan4Disease backend. It is
/// careful to honour the response contract exactly:
///   * `probabilities` is a LIST of {code, name, probability, malignancy}
///   * `triage` is an OBJECT {category, label, advice, reasons, low_confidence}
///   * `confidence` is a model score, never presented as a disease probability
///   * the Grad-CAM overlay is fetched from an absolute URL the API client set
///   * the fixed disclaimer comes from the backend (falls back to a local copy)
class DiagnosisResultsUI extends StatelessWidget {
  const DiagnosisResultsUI({super.key, required this.diagnosisData, this.report});
  final Map<String, dynamic> diagnosisData;

  /// The saved screening this result belongs to, when opened straight after a scan. Present
  /// (with an id and a device-local image) it enables the "share with a doctor" card; null
  /// (e.g. viewing an old report from history whose local image is gone) hides it.
  final ScreeningReport? report;

  bool get _canShare => report?.id != null && (report?.imagePath ?? '').isNotEmpty;

  static const String _fallbackDisclaimer =
      'IMPORTANT\n\nThis result is generated by an AI screening system and is not a '
      'medical diagnosis. Please consult a qualified dermatologist for professional '
      'evaluation, especially if the lesion is new, changing, painful, bleeding, or '
      'otherwise concerning.';

  @override
  Widget build(BuildContext context) {
    final outcome = _string('outcome', 'lesion');
    final isLesion = outcome == 'lesion';

    final isHindi = LanguageService.instance.code.value == 'hi' ||
        diagnosisData['language'] == 'hi';

    final name = _string('predicted_name', _string('predicted_class', isHindi ? 'स्क्रीनिंग परिणाम' : 'Screening result'));
    final code = isLesion ? _string('predicted_class', '') : '';
    final confidence = isLesion ? _double('confidence') : null;
    final stub = diagnosisData['stub'] == true;

    return ValueListenableBuilder<ThemeMode>(
      valueListenable: ThemeService.instance.mode,
      builder: (context, __, ___) {
        final dark = ThemeService.instance.isDark(context);
        return Scaffold(
          extendBodyBehindAppBar: true,
          appBar: AppBar(
            backgroundColor: dark
                ? const Color(0xFF161920).withValues(alpha: 0.72)
                : Colors.white.withValues(alpha: 0.85),
            foregroundColor: dark ? Themes.darkInk : Themes.ink,
            elevation: 0,
            scrolledUnderElevation: 1,
            title: Text(isHindi ? 'स्क्रीनिंग परिणाम' : 'Screening result'),
            actions: [
              if (report != null)
                IconButton(
                  tooltip: isHindi ? 'डॉक्टर सारांश' : 'Doctor summary',
                  icon: const Icon(Icons.summarize_outlined),
                  onPressed: () => showReportSummarySheet(context, report!),
                ),
            ],
          ),
          body: Stack(
            fit: StackFit.expand,
            children: [
              const VideoBackground.ambient(),
              SafeArea(
                child: ListView(
                  padding: const EdgeInsets.fromLTRB(18, 12, 18, 32),
                  children: [
                    if (stub) _stubBanner(),
                    _headline(name, code, confidence, isHindi),
                    const SizedBox(height: 16),
                    _lesionCard(dark, isHindi),
                    _triageCard(dark, isHindi),
                    const SizedBox(height: 14),
                    if (_canShare) ...[
                      _shareCard(context, dark, isHindi),
                      const SizedBox(height: 14),
                    ],
                    _askCard(context, dark, isHindi),
                    const SizedBox(height: 14),
                    FindDoctorCard(subtitle: _doctorSubtitle(outcome, isHindi)),
                    const SizedBox(height: 14),
                    _gradcamCard(dark, isHindi),
                    if (isLesion) _explanationCard(dark, isHindi),
                    _probabilitiesCard(dark, isHindi),
                    const SizedBox(height: 14),
                    UnderstandResultBar(
                      confidence: confidence,
                      triage: diagnosisData['triage'] is Map ? diagnosisData['triage'] as Map : null,
                      hasHeatmap: (diagnosisData['gradcam_display_url']?.toString() ?? '').isNotEmpty,
                      isLesion: isLesion,
                      isHindi: isHindi,
                    ),
                    const SizedBox(height: 14),
                    _disclaimerCard(dark),
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  // --- share-with-a-doctor CTA -----------------------------------------------

  Widget _shareCard(BuildContext context, bool dark, bool isHindi) => Container(
        clipBehavior: Clip.antiAlias,
        decoration: Themes.liquidGlassDecoration(radius: 20, dark: dark),
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: () => showShareWithDoctorSheet(
              context,
              report!,
              gradcamUrl: diagnosisData['gradcam_display_url']?.toString(),
            ),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: (dark ? Themes.tealGlow : Themes.brand).withValues(alpha: 0.14),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: dark ? Themes.tealGlow.withValues(alpha: 0.28) : Colors.white.withValues(alpha: 0.85),
                    ),
                  ),
                  child: Icon(Icons.medical_services_outlined, color: dark ? Themes.tealLight : Themes.brand, size: 22),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text(
                      isHindi ? 'सत्यापित डॉक्टर से साझा करें' : 'Share with a verified doctor',
                      style: TextStyle(color: dark ? Themes.darkInk : Themes.ink, fontWeight: FontWeight.w800, fontSize: 15),
                    ),
                    const SizedBox(height: 3),
                    Text(
                      isHindi
                          ? 'विशेषज्ञ समीक्षा के लिए इस स्क्रीनिंग और तस्वीर को त्वचा रोग विशेषज्ञ को भेजें।'
                          : 'Send this screening and image to a dermatologist for clinical review.',
                      style: TextStyle(color: dark ? Themes.darkInkSoft : Themes.inkSoft, height: 1.35, fontSize: 12.5),
                    ),
                  ]),
                ),
                Icon(Icons.chevron_right_rounded, color: dark ? Themes.tealLight : Themes.brand),
              ]),
            ),
          ),
        ),
      );

  // --- ask-the-assistant CTA -------------------------------------------------

  Widget _askCard(BuildContext context, bool dark, bool isHindi) => Container(
        clipBehavior: Clip.antiAlias,
        decoration: Themes.liquidGlassDecoration(radius: 20, dark: dark),
        child: Material(
          color: Colors.transparent,
          child: InkWell(
            onTap: () => _openChat(context),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(children: [
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: (dark ? Themes.tealGlow : Themes.brand).withValues(alpha: 0.14),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: dark ? Themes.tealGlow.withValues(alpha: 0.28) : Colors.white.withValues(alpha: 0.85),
                    ),
                  ),
                  child: Icon(Icons.forum_outlined, color: dark ? Themes.tealLight : Themes.brand, size: 22),
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Wrap(
                      crossAxisAlignment: WrapCrossAlignment.center,
                      spacing: 8,
                      runSpacing: 4,
                      children: [
                        Text(
                          isHindi ? 'इस परिणाम के बारे में पूछें' : 'Ask about this result',
                          style: TextStyle(fontWeight: FontWeight.w800, fontSize: 15, color: dark ? Themes.darkInk : Themes.ink),
                        ),
                        Container(
                          padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
                          decoration: BoxDecoration(
                            color: dark ? Themes.darkBrandTint : Themes.brandTint.withValues(alpha: 0.75),
                            borderRadius: const BorderRadius.all(Radius.circular(6)),
                            border: Border.all(
                              color: dark ? Themes.tealGlow.withValues(alpha: 0.28) : Colors.white.withValues(alpha: 0.85),
                            ),
                          ),
                          child: Text(
                            isHindi ? 'AI सहायक' : 'AI Assistant',
                            style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: dark ? Themes.tealLight : Themes.brand),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 3),
                    Text(
                      isHindi
                          ? 'परिणाम को समझने और अगले कदमों के लिए AI सहायक से चर्चा करें।'
                          : 'Chat with the assistant to understand what it means and recommended next steps.',
                      style: TextStyle(color: dark ? Themes.darkInkSoft : Themes.inkSoft, height: 1.35, fontSize: 12.5),
                    ),
                  ]),
                ),
                Icon(Icons.chevron_right_rounded, color: dark ? Themes.tealLight : Themes.brand),
              ]),
            ),
          ),
        ),
      );

  void _openChat(BuildContext context) {
    final triage = diagnosisData['triage'];
    final prediction = <String, dynamic>{
      'predicted_class': _string('predicted_class', ''),
      'confidence': _double('confidence') ?? 0.0,
      'triage_category': (triage is Map ? triage['category']?.toString() : '') ?? '',
      'low_confidence': triage is Map && triage['low_confidence'] == true,
      if (_string('gradcam_focus', '').isNotEmpty) 'gradcam_focus': _string('gradcam_focus', ''),
    };
    final q = diagnosisData['questionnaire'];
    final questionnaire = q is Map ? Map<String, dynamic>.from(q) : null;
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ChatScreen(
          prediction: prediction,
          questionnaire: questionnaire,
          conditionName: _string('predicted_name', ''),
        ),
      ),
    );
  }

  String _doctorSubtitle(String outcome, bool isHindi) => switch (outcome) {
        'healthy' => isHindi
            ? 'यहाँ कोई चिंताजनक घाव नहीं मिला, लेकिन डॉक्टर व्यक्तिगत रूप से जाँच कर सकते हैं।'
            : 'Nothing concerning was found here, but a dermatologist can examine your skin in person.',
        'other_damage' => isHindi
            ? 'यदि घाव ठीक न हो, या दर्द, सूजन या संक्रमण हो तो डॉक्टर से मिलें।'
            : 'See a doctor if the wound does not heal, or becomes painful, swollen, or infected.',
        _ => isHindi
            ? 'अपने नजदीकी त्वचा रोग विशेषज्ञ से इसकी पेशेवर जाँच कराएँ।'
            : 'Have this professionally examined by a dermatologist near you.',
      };

  // --- header with the model score ------------------------------------------

  // --- header with the model score ------------------------------------------

  Widget _headline(String name, String code, double? confidence, bool isHindi) => Container(
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          gradient: const LinearGradient(
            colors: [Themes.brand, Themes.brandDark],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
          borderRadius: BorderRadius.circular(22),
          border: Border.all(color: Colors.white.withValues(alpha: 0.35), width: 1.2),
          boxShadow: [
            BoxShadow(
              color: Themes.brand.withValues(alpha: 0.30),
              blurRadius: 22,
              offset: const Offset(0, 8),
            ),
            BoxShadow(
              color: Colors.white.withValues(alpha: 0.20),
              blurRadius: 4,
              spreadRadius: 0.5,
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(children: [
              const AppLogoMark(size: 22, color: Colors.white, holeColor: Colors.transparent, glow: false),
              const SizedBox(width: 8),
              Text(
                isHindi ? 'मॉडल मूल्यांकन' : 'MODEL ASSESSMENT',
                style: const TextStyle(color: Colors.white, fontSize: 10.5, fontWeight: FontWeight.w700, letterSpacing: 0.5),
              ),
            ]),
            const SizedBox(height: 12),
            Text(name,
                style: const TextStyle(color: Colors.white, fontSize: 25, fontWeight: FontWeight.w800, letterSpacing: -0.01)),
            if (code.isNotEmpty)
              Padding(
                padding: const EdgeInsets.only(top: 2),
                child: Text(
                  isHindi ? 'मॉडल वर्ग कोड: ${code.toUpperCase()}' : 'Model class code: ${code.toUpperCase()}',
                  style: const TextStyle(color: Colors.white70, fontSize: 12, letterSpacing: 0.8),
                ),
              ),
            if (confidence != null) ...[
              const SizedBox(height: 16),
              ClipRRect(
                borderRadius: BorderRadius.circular(6),
                child: LinearProgressIndicator(
                  value: confidence.clamp(0, 1),
                  minHeight: 8,
                  backgroundColor: Colors.white24,
                  color: Colors.white,
                ),
              ),
              const SizedBox(height: 8),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(isHindi ? 'मिलान स्कोर' : 'Match score', style: const TextStyle(color: Colors.white70, fontSize: 12.5)),
                  Text('${(confidence * 100).toStringAsFixed(1)}%',
                      style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w800, fontSize: 14)),
                ],
              ),
              const SizedBox(height: 2),
              Text(
                isHindi
                    ? 'यह एक मिलान स्कोर है — यह आपके रोगग्रस्त होने की संभावना नहीं है।'
                    : 'A match score — not the probability that you have this condition.',
                style: const TextStyle(color: Colors.white70, fontSize: 11.5, height: 1.3),
              ),
            ],
          ],
        ),
      );

  // --- triage (colour-coded by urgency) -------------------------------------

  Widget _triageCard(bool dark, bool isHindi) {
    final triage = diagnosisData['triage'];
    if (triage is! Map) return const SizedBox.shrink();

    final category = triage['category']?.toString() ?? '';
    final label = triage['label']?.toString() ?? (isHindi ? 'पेशेवर समीक्षा अनुशंसित' : 'Professional review recommended');
    final advice = triage['advice']?.toString() ?? '';
    final reasons = (triage['reasons'] is List) ? List.from(triage['reasons']) : const [];
    final lowConfidence = triage['low_confidence'] == true;

    final (color, bg, border, icon) = switch (category) {
      'urgent_evaluation' => (
          Themes.urgent,
          dark ? const Color(0xFF2B1315) : Themes.urgentBg,
          dark ? const Color(0xFF6B2127) : Themes.urgentBorder,
          Icons.priority_high_rounded
        ),
      'prompt_consultation' => (
          Themes.soon,
          dark ? const Color(0xFF281E09) : Themes.soonBg,
          dark ? const Color(0xFF5D430C) : Themes.soonBorder,
          Icons.schedule_rounded
        ),
      _ => (
          dark ? Themes.tealLight : Themes.routine,
          dark ? const Color(0xFF102722) : Themes.routineBg,
          dark ? const Color(0xFF1B594C) : Themes.routineBorder,
          Icons.check_circle_outline_rounded
        ),
    };

    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            bg.withValues(alpha: dark ? 0.95 : 0.85),
            bg.withValues(alpha: dark ? 0.85 : 0.65),
          ],
        ),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(
          color: dark ? border : Colors.white.withValues(alpha: 0.85),
          width: 1.2,
        ),
        boxShadow: [
          BoxShadow(
            color: dark ? border.withValues(alpha: 0.20) : Colors.white.withValues(alpha: 0.50),
            blurRadius: 4,
            spreadRadius: 0.5,
          ),
          BoxShadow(
            color: Colors.black.withValues(alpha: dark ? 0.35 : 0.06),
            blurRadius: 18,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            Container(
              padding: const EdgeInsets.all(6),
              decoration: BoxDecoration(
                color: color.withValues(alpha: dark ? 0.22 : 0.15),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, color: color, size: 18),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Text(label,
                  style: TextStyle(fontSize: 16, fontWeight: FontWeight.w800, color: color)),
            ),
          ]),
          if (advice.isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(advice, style: TextStyle(height: 1.4, color: dark ? Themes.darkInk : Themes.ink, fontSize: 13.5)),
          ],
          if (lowConfidence) ...[
            const SizedBox(height: 10),
            Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
              Icon(Icons.info_outline, size: 16, color: dark ? Themes.darkInkSoft : Themes.inkSoft),
              const SizedBox(width: 6),
              Expanded(child: Text(
                isHindi
                    ? 'मॉडल इस तस्वीर को लेकर आश्वस्त नहीं था — पेशेवर जाँच पर भरोसा करें।'
                    : 'The model was not confident about this image — rely on a professional examination.',
                style: TextStyle(fontSize: 12.5, color: dark ? Themes.darkInkSoft : Themes.inkSoft),
              )),
            ]),
          ],
          if (reasons.isNotEmpty) ...[
            const SizedBox(height: 12),
            Text(
              isHindi ? 'मूल्यांकन किए गए चिकित्सीय मानदंड:' : 'Clinical criteria evaluated:',
              style: TextStyle(fontWeight: FontWeight.w700, fontSize: 13, color: dark ? Themes.darkInk : Themes.ink),
            ),
            const SizedBox(height: 6),
            ...reasons.map((r) => Padding(
                  padding: const EdgeInsets.only(bottom: 4),
                  child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Text('•  ', style: TextStyle(color: dark ? Themes.darkInkSoft : Themes.inkSoft)),
                    Expanded(child: Text(r.toString(),
                        style: TextStyle(height: 1.35, fontSize: 13, color: dark ? Themes.darkInk : Themes.ink))),
                  ]),
                )),
          ],
        ],
      ),
    );
  }

  // --- screened photograph ---------------------------------------------------

  Widget _lesionCard(bool dark, bool isHindi) {
    final path = report?.imagePath ?? '';
    if (path.isEmpty) return const SizedBox.shrink();
    final file = File(path);
    if (!file.existsSync()) return const SizedBox.shrink();

    final image = ClipRRect(
      borderRadius: BorderRadius.circular(14),
      child: Image.file(
        file,
        height: 220,
        width: double.infinity,
        fit: BoxFit.cover,
        errorBuilder: (_, __, ___) => const SizedBox.shrink(),
      ),
    );

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section(
        isHindi ? 'जाँची गई तस्वीर' : 'Screened photograph',
        report?.id == null
            ? image
            : Hero(tag: 'lesion-${report!.id}', child: image),
        dark: dark,
      ),
    );
  }

  // --- Grad-CAM overlay ------------------------------------------------------

  Widget _gradcamCard(bool dark, bool isHindi) {
    final url = diagnosisData['gradcam_display_url']?.toString();
    if (url == null || url.isEmpty) return const SizedBox.shrink();
    final focus = _string('gradcam_focus', '');

    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section(
        isHindi ? 'मॉडल विज़ुअल अटेंशन (Grad-CAM)' : 'Model visual attention (Grad-CAM)',
        Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(12),
              child: Image.network(
                url,
                height: 220,
                width: double.infinity,
                fit: BoxFit.cover,
                loadingBuilder: (c, child, progress) => progress == null
                    ? child
                    : const SizedBox(height: 220, child: Center(child: CircularProgressIndicator())),
                frameBuilder: (_, child, frame, wasSync) {
                  if (wasSync) return child;
                  return AnimatedOpacity(
                    opacity: frame == null ? 0 : 1,
                    duration: const Duration(milliseconds: 260),
                    curve: Curves.easeOutCubic,
                    child: child,
                  );
                },
                errorBuilder: (c, e, s) => SizedBox(
                  height: 100,
                  child: Center(
                    child: Text(
                      isHindi ? 'हीटमैप अनुपलब्ध है।' : 'Heatmap unavailable (temporary asset expired).',
                      style: TextStyle(color: dark ? Themes.darkInkSoft : Themes.inkSoft, fontSize: 12),
                    ),
                  ),
                ),
              ),
            ),
            if (focus.isNotEmpty) ...[
              const SizedBox(height: 8),
              Text(
                isHindi ? 'ध्यान केंद्रित: $focus.' : 'Attention concentrated: $focus.',
                style: TextStyle(color: dark ? Themes.darkInkSoft : Themes.inkSoft, fontSize: 12.5),
              ),
            ],
            const SizedBox(height: 4),
            Text(
              isHindi
                  ? 'हाइलाइट किए गए क्षेत्रों ने मॉडल के परिणाम को प्रभावित किया। यह व्याख्या सहायता है, नैदानिक प्रमाण नहीं।'
                  : 'Highlighted regions influenced the model output. This is an explainability aid, not proof of clinical reasoning.',
              style: TextStyle(color: dark ? Themes.darkInkSoft : Themes.inkSoft, fontSize: 11.5, height: 1.3),
            ),
          ],
        ),
        dark: dark,
      ),
    );
  }

  // --- explanation -----------------------------------------------------------

  Widget _explanationCard(bool dark, bool isHindi) {
    final available = diagnosisData['explanation_available'] == true;
    final explanation = _string(
      'explanation',
      available ? '' : (isHindi ? 'व्याख्या सेवा ऑफ़लाइन है। ऊपर दिया गया परिणाम अप्रभावित है।' : 'The written explanation service is offline. The result above is unaffected.'),
    );
    if (explanation.isEmpty) return const SizedBox.shrink();
    return Padding(
      padding: const EdgeInsets.only(bottom: 14),
      child: _section(
        isHindi ? 'चिकित्सीय व्याख्या' : 'Clinical explanation',
        MarkdownText(explanation, color: dark ? Themes.darkInk : Themes.ink),
        dark: dark,
      ),
    );
  }

  // --- per-class scores (LIST from the backend) ------------------------------

  Widget _probabilitiesCard(bool dark, bool isHindi) {
    final probs = diagnosisData['probabilities'];
    if (probs is! List || probs.isEmpty) return const SizedBox.shrink();

    return _section(
      isHindi ? 'सभी श्रेणियों के मिलान स्कोर' : 'All category match scores',
      Column(
        children: [
          for (final p in probs)
            if (p is Map) _probRow(p, dark),
        ],
      ),
      dark: dark,
    );
  }

  Widget _probRow(Map p, bool dark) {
    final name = p['name']?.toString() ?? p['code']?.toString() ?? '—';
    final value = p['probability'] is num ? (p['probability'] as num).toDouble() : 0.0;
    final malignancy = p['malignancy']?.toString() ?? 'benign';
    final color = switch (malignancy) {
      'malignant' => Themes.urgent,
      'premalignant' => Themes.soon,
      _ => dark ? Themes.tealLight : Themes.routine,
    };

    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Column(
        children: [
          Row(children: [
            Expanded(
              child: Text(
                name,
                style: TextStyle(
                  fontSize: 13.5,
                  color: dark ? Themes.darkInk : Themes.ink,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            Text(
              '${(value * 100).toStringAsFixed(1)}%',
              style: TextStyle(
                fontWeight: FontWeight.w700,
                fontSize: 13,
                color: dark ? Themes.darkInk : Themes.ink,
              ),
            ),
          ]),
          const SizedBox(height: 5),
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value: value.clamp(0, 1),
              minHeight: 6,
              backgroundColor: dark ? Themes.darkBorder : Themes.border,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  // --- disclaimer + stub -----------------------------------------------------

  Widget _disclaimerCard(bool dark) {
    final text = _string('disclaimer', _fallbackDisclaimer);
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: Themes.liquidGlassDecoration(radius: 16, dark: dark),
      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Icon(Icons.shield_outlined, color: dark ? Themes.tealLight : Themes.warning, size: 20),
        const SizedBox(width: 10),
        Expanded(
          child: Text(
            text,
            style: TextStyle(height: 1.4, color: dark ? Themes.darkInk : Themes.ink, fontSize: 12.5),
          ),
        ),
      ]),
    );
  }

  Widget _stubBanner() => Container(
        margin: const EdgeInsets.only(bottom: 14),
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Themes.danger.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: Themes.danger.withValues(alpha: 0.4)),
        ),
        child: const Row(children: [
          Icon(Icons.science_outlined, color: Themes.danger),
          SizedBox(width: 10),
          Expanded(child: Text(
            'Demo/stub mode: these values are placeholders, not a real model prediction.',
            style: TextStyle(color: Themes.danger, fontWeight: FontWeight.w600),
          )),
        ]),
      );

  // --- helpers ---------------------------------------------------------------

  Widget _section(String title, Widget child, {bool dark = false}) => Container(
        margin: const EdgeInsets.only(bottom: 14),
        decoration: Themes.liquidGlassDecoration(radius: 20, dark: dark),
        child: Padding(
          padding: const EdgeInsets.all(17),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: TextStyle(
                  fontSize: 17,
                  fontWeight: FontWeight.w800,
                  color: dark ? Themes.darkInk : Themes.ink,
                ),
              ),
              const SizedBox(height: 12),
              child,
            ],
          ),
        ),
      );

  String _string(String key, String fallback) {
    final v = diagnosisData[key];
    return (v == null || v.toString().isEmpty) ? fallback : v.toString();
  }

  double? _double(String key) {
    final v = diagnosisData[key];
    if (v is num) return v.toDouble();
    return double.tryParse(v?.toString() ?? '');
  }
}

/// "Understand this result" — an expandable bar at the foot of every screening result.
class UnderstandResultBar extends StatelessWidget {
  const UnderstandResultBar({
    super.key,
    required this.confidence,
    required this.triage,
    required this.hasHeatmap,
    required this.isLesion,
    this.isHindi = false,
  });

  final double? confidence;
  final Map? triage;
  final bool hasHeatmap;
  final bool isLesion;
  final bool isHindi;

  String get _category => triage?['category']?.toString() ?? '';
  bool get _lowConfidence => triage?['low_confidence'] == true;

  @override
  Widget build(BuildContext context) {
    final dark = Theme.of(context).brightness == Brightness.dark;
    final primaryColor = dark ? Themes.tealLight : Themes.primary;
    final ink = dark ? Themes.darkInk : Themes.ink;
    final muted = dark ? Themes.darkInkSoft : Themes.muted;

    return Container(
      clipBehavior: Clip.antiAlias,
      decoration: Themes.liquidGlassDecoration(radius: 20, dark: dark),
      child: Theme(
        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
          expandedCrossAxisAlignment: CrossAxisAlignment.start,
          leading: Container(
            padding: const EdgeInsets.all(9),
            decoration: BoxDecoration(
              color: primaryColor.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Icon(Icons.school_outlined, color: primaryColor),
          ),
          title: Text(
            isHindi ? 'इस परिणाम को समझें' : 'Understand this result',
            style: TextStyle(fontWeight: FontWeight.w800, fontSize: 16, color: ink),
          ),
          subtitle: Padding(
            padding: const EdgeInsets.only(top: 2),
            child: Text(
              isHindi ? 'यह स्कोर और ट्राइएज आपके लिए वास्तव में क्या मायने रखते हैं।' : 'What the score and triage actually mean for you.',
              style: TextStyle(color: muted, fontSize: 12.5, height: 1.3),
            ),
          ),
          children: [
            if (confidence != null)
              _point(
                Icons.percent_rounded,
                isHindi
                    ? '${(confidence! * 100).toStringAsFixed(1)}% एक मिलान स्कोर है, कोई निश्चित निदान नहीं'
                    : 'The ${(confidence! * 100).toStringAsFixed(1)}% is a match score, not a diagnosis',
                isHindi
                    ? 'इसका मतलब है कि तस्वीर इस श्रेणी से सबसे अधिक मिलती-जुलती है। यह आपके इस रोग से ग्रस्त होने की संभावना नहीं है।'
                    : 'It means the image resembled this category more than the others the model knows. It is not the chance that you have this condition, and the model can only pick from the classes it was trained on.',
                dark,
              ),
            if (_category.isNotEmpty) _point(Icons.flag_outlined, _triageTitle(), _triageBody(), dark),
            if (_lowConfidence)
              _point(
                Icons.help_outline_rounded,
                isHindi ? 'विश्वास कम था — इसे "अस्पष्ट" मानें' : 'Confidence was low — treat this as "unclear"',
                isHindi
                    ? 'धुंधलापन, कम रोशनी या असामान्य घाव से विश्वास कम हो जाता है। कृपया बेहतर रोशनी में दोबारा फोटो लें या जाँच कराएँ।'
                    : 'Blur, poor lighting, hair or an unfamiliar lesion all reduce confidence. A low-confidence result is not a clean bill of health: retake the photo in better light, or have it examined.',
                dark,
              ),
            if (hasHeatmap)
              _point(
                Icons.blur_on_rounded,
                isHindi ? 'हीटमैप को ध्यान के रूप में पढ़ें, प्रमाण नहीं' : 'Read the heatmap as attention, not proof',
                isHindi
                    ? 'गर्म रंग उन हिस्सों को दर्शाते हैं जिन्होंने मॉडल के निर्णय को प्रभावित किया।'
                    : 'Warm colours mark what influenced the output. Heat centred on the lesion is reassuring; heat on background skin or hair means the model may have keyed on an artefact, so weigh the result accordingly.',
                dark,
              ),
            _point(
              Icons.check_circle_outline_rounded,
              isHindi ? 'आगे क्या करें' : 'What to do next',
              isHindi
                  ? 'हर महीने उसी जगह की तस्वीर लें ताकि बदलाव आसानी से दिख सके, और घाव बढ़ने या बदलने पर डॉक्टर से मिलें।'
                  : (isLesion
                      ? 'Photograph the same spot monthly so change is easy to see, and book a dermatologist if it grows, changes colour, bleeds or itches — regardless of what this screen said.'
                      : 'Keep an eye on the area and seek care if it worsens, fails to heal, or becomes painful, swollen or infected.'),
              dark,
            ),
            const SizedBox(height: 4),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton.icon(
                onPressed: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (_) => const SkinGuideScreen(focusResults: true)),
                ),
                icon: const Icon(Icons.menu_book_outlined, size: 18),
                label: Text(isHindi ? 'त्वचा स्वास्थ्य गाइड खोलें' : 'Open the full skin health guide'),
              ),
            ),
          ],
        ),
      ),
    );
  }

  String _triageTitle() => switch (_category) {
        'urgent_evaluation' => isHindi ? 'तत्काल मूल्यांकन — कुछ ही दिनों में कार्रवाई करें' : 'Urgent evaluation — act on this within days',
        'prompt_consultation' => isHindi ? 'शीघ्र परामर्श — जल्द अपॉइंटमेंट बुक करें' : 'Prompt consultation — book an appointment soon',
        _ => isHindi ? 'नियमित निगरानी — इस स्थान पर नज़र बनाए रखें' : 'Routine monitoring — keep watching this spot',
      };

  String _triageBody() => switch (_category) {
        'urgent_evaluation' => isHindi
            ? 'ट्राइएज श्रेणी सावधानीपूर्वक तय की गई है। किसी भी गंभीर घाव की जल्द जाँच कराना सबसे सुरक्षित है।'
            : 'The triage band is the part to act on. It is set cautiously and can be more urgent than the top prediction alone suggests — that is deliberate, because missing a serious lesion is far costlier than an unnecessary visit.',
        'prompt_consultation' => isHindi
            ? 'अगले कुछ हफ़्तों में पेशेवर जाँच कराएँ।'
            : 'Arrange a professional look in the next few weeks. This band means the findings are not clearly benign, not that something is definitely wrong.',
        _ => isHindi
            ? 'यहाँ किसी तत्काल कार्रवाई की आवश्यकता नहीं है, फिर भी मासिक रूप से जाँच करते रहें।'
            : 'Nothing here demanded urgent action, but screening cannot rule anything out. Re-check monthly and escalate on any change.',
      };

  Widget _point(IconData icon, String title, String body, bool dark) => Padding(
        padding: const EdgeInsets.only(bottom: 14),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Padding(
              padding: const EdgeInsets.only(top: 2),
              child: Icon(icon, size: 17, color: dark ? Themes.tealLight : Themes.primary),
            ),
            const SizedBox(width: 9),
            Expanded(
              child: Text(title,
                  style: TextStyle(
                    fontWeight: FontWeight.w800,
                    height: 1.3,
                    color: dark ? Themes.darkInk : Themes.ink,
                  )),
            ),
          ]),
          const SizedBox(height: 4),
          Padding(
            padding: const EdgeInsets.only(left: 26),
            child: Text(body,
                style: TextStyle(
                  color: dark ? Themes.darkInkSoft : Themes.muted,
                  height: 1.45,
                  fontSize: 12.8,
                )),
          ),
        ]),
      );
}
