"""Fixed safety text, owned by the application.

Master specification, section 27: the mandatory warning must be implemented in the
application itself and must not depend on the LLM producing it. Every string in this file
is a constant. None of it is generated, and none of it passes through the language model
on its way to the user -- including the Hindi versions, which are translated here once
rather than at request time.

That last point matters. If the LLM translated the disclaimer per request, an unlucky
sample could soften "this is not a medical diagnosis" into something weaker, and nobody
would notice.
"""

from __future__ import annotations

from backend.app.schemas.common import Language, Outcome, TriageCategory

DISCLAIMERS: dict[Language, str] = {
    Language.ENGLISH: (
        "IMPORTANT\n\n"
        "This result is generated by an AI screening system and is not a medical diagnosis.\n\n"
        "Please consult a qualified dermatologist for professional evaluation, especially if "
        "the lesion is new, changing, painful, bleeding, or otherwise concerning."
    ),
    Language.HINDI: (
        "महत्वपूर्ण\n\n"
        "यह परिणाम एक AI स्क्रीनिंग प्रणाली द्वारा तैयार किया गया है और यह चिकित्सकीय निदान नहीं है।\n\n"
        "कृपया पेशेवर मूल्यांकन के लिए किसी योग्य त्वचा रोग विशेषज्ञ से परामर्श करें, "
        "विशेष रूप से यदि घाव नया है, बदल रहा है, दर्दनाक है, उसमें से खून आ रहा है, "
        "या किसी अन्य कारण से चिंताजनक है।"
    ),
}

TRIAGE_LABELS: dict[TriageCategory, dict[Language, str]] = {
    TriageCategory.ROUTINE: {
        Language.ENGLISH: "Routine dermatologist consultation",
        Language.HINDI: "सामान्य त्वचा रोग विशेषज्ञ परामर्श",
    },
    TriageCategory.PROMPT: {
        Language.ENGLISH: "Prompt dermatologist consultation",
        Language.HINDI: "शीघ्र त्वचा रोग विशेषज्ञ परामर्श",
    },
    TriageCategory.URGENT: {
        Language.ENGLISH: "Urgent medical evaluation",
        Language.HINDI: "तत्काल चिकित्सा मूल्यांकन",
    },
}

TRIAGE_ADVICE: dict[TriageCategory, dict[Language, str]] = {
    TriageCategory.ROUTINE: {
        Language.ENGLISH: (
            "Nothing in this screening suggests urgency. Mention this lesion at your next "
            "routine visit to a doctor or dermatologist. If it starts to change, grow, bleed "
            "or become painful, arrange an appointment sooner."
        ),
        Language.HINDI: (
            "इस स्क्रीनिंग में तत्काल चिंता का कोई संकेत नहीं मिला। डॉक्टर या त्वचा विशेषज्ञ के पास "
            "अपनी अगली सामान्य मुलाक़ात में इस घाव का ज़िक्र करें। यदि यह बदलने, बढ़ने, खून आने या "
            "दर्द होने लगे, तो जल्दी अपॉइंटमेंट लें।"
        ),
    },
    TriageCategory.PROMPT: {
        Language.ENGLISH: (
            "Please arrange to see a dermatologist soon rather than waiting for a routine "
            "appointment. This is a precaution: a professional examination can assess this "
            "lesion properly in a way that a photograph cannot."
        ),
        Language.HINDI: (
            "कृपया सामान्य अपॉइंटमेंट की प्रतीक्षा किए बिना जल्द ही किसी त्वचा रोग विशेषज्ञ से मिलें। "
            "यह एहतियात के तौर पर है: पेशेवर जाँच इस घाव का सही आकलन कर सकती है, जो एक तस्वीर "
            "से संभव नहीं है।"
        ),
    },
    TriageCategory.URGENT: {
        Language.ENGLISH: (
            "Please seek medical evaluation without delay. Contact a dermatologist, a doctor, "
            "or your nearest health centre as soon as you reasonably can. Conditions of this "
            "kind are treatable, and outcomes are generally better when they are examined early."
        ),
        Language.HINDI: (
            "कृपया बिना देरी किए चिकित्सा मूल्यांकन कराएँ। जितनी जल्दी संभव हो, किसी त्वचा रोग "
            "विशेषज्ञ, डॉक्टर या अपने निकटतम स्वास्थ्य केंद्र से संपर्क करें। इस प्रकार की स्थितियाँ "
            "उपचार योग्य होती हैं, और जल्दी जाँच होने पर परिणाम आमतौर पर बेहतर होते हैं।"
        ),
    },
}

# How to talk about the confidence number. Master specification, section 16: never
# "there is an 84% chance you have melanoma".
CONFIDENCE_PHRASING: dict[Language, str] = {
    Language.ENGLISH: (
        "The model assigned its highest prediction score ({percent}%) to the {name} class. "
        "This score describes how strongly the image matched that category in the model's "
        "training data. It is not the probability that you have this condition."
    ),
    Language.HINDI: (
        "मॉडल ने अपना सर्वोच्च पूर्वानुमान स्कोर ({percent}%) {name} श्रेणी को दिया। "
        "यह स्कोर बताता है कि तस्वीर मॉडल के प्रशिक्षण डेटा में उस श्रेणी से कितनी मिलती-जुलती है। "
        "यह इस बात की संभावना नहीं है कि आपको यह स्थिति है।"
    ),
}

LOW_CONFIDENCE_NOTICE: dict[Language, str] = {
    Language.ENGLISH: (
        "The model was not confident about this image. Treat the suggested category as weak "
        "information only, and rely on a professional examination."
    ),
    Language.HINDI: (
        "मॉडल इस तस्वीर के बारे में आश्वस्त नहीं था। सुझाई गई श्रेणी को केवल कमज़ोर जानकारी मानें "
        "और पेशेवर जाँच पर भरोसा करें।"
    ),
}

QUALITY_REJECTION: dict[Language, str] = {
    Language.ENGLISH: (
        "Image quality is insufficient for screening. Please capture a clearer, well-lit "
        "image with the lesion in focus and filling most of the frame."
    ),
    Language.HINDI: (
        "स्क्रीनिंग के लिए तस्वीर की गुणवत्ता पर्याप्त नहीं है। कृपया अच्छी रोशनी में एक स्पष्ट "
        "तस्वीर लें, जिसमें घाव फ़ोकस में हो और फ़्रेम का अधिकांश भाग घेरता हो।"
    ),
}

LLM_UNAVAILABLE_NOTICE: dict[Language, str] = {
    Language.ENGLISH: (
        "The explanation service is currently unavailable, so no written explanation could be "
        "produced. The classification result and the guidance above are unaffected."
    ),
    Language.HINDI: (
        "व्याख्या सेवा इस समय उपलब्ध नहीं है, इसलिए कोई लिखित व्याख्या तैयार नहीं की जा सकी। "
        "वर्गीकरण परिणाम और ऊपर दिया गया मार्गदर्शन इससे प्रभावित नहीं हुआ है।"
    ),
}


# Fixed, application-owned text for the non-lesion router outcomes. These short-circuit the
# disease pipeline, so their wording carries the whole safety burden: "healthy" must never
# read as an all-clear, and "other damage" must not imply the tool assessed the wound.
OUTCOME_NAMES: dict[Outcome, dict[Language, str]] = {
    Outcome.HEALTHY: {
        Language.ENGLISH: "No concerning lesion detected",
        Language.HINDI: "कोई चिंताजनक घाव नहीं मिला",
    },
    Outcome.OTHER_DAMAGE: {
        Language.ENGLISH: "Wound or skin injury",
        Language.HINDI: "घाव या त्वचा की चोट",
    },
}

OUTCOME_ADVICE: dict[Outcome, dict[Language, str]] = {
    Outcome.HEALTHY: {
        Language.ENGLISH: (
            "This screening did not find a skin lesion of the kind this tool recognises. "
            "This is NOT a medical clearance and cannot rule out a skin condition. If you "
            "can see or feel something on your skin, or if an area changes, grows, bleeds, "
            "or becomes painful, have it examined by a doctor or dermatologist."
        ),
        Language.HINDI: (
            "इस स्क्रीनिंग में इस उपकरण द्वारा पहचाने जाने वाले प्रकार का कोई त्वचा घाव नहीं मिला। "
            "यह चिकित्सकीय प्रमाणन नहीं है और किसी त्वचा रोग को खारिज नहीं कर सकता। यदि आपको अपनी "
            "त्वचा पर कुछ दिखता या महसूस होता है, या कोई हिस्सा बदलता, बढ़ता, उससे खून आता या दर्द "
            "होता है, तो किसी डॉक्टर या त्वचा रोग विशेषज्ञ से जाँच कराएँ।"
        ),
    },
    Outcome.OTHER_DAMAGE: {
        Language.ENGLISH: (
            "This looks like a wound, graze, bruise, or other skin damage rather than one of "
            "the conditions this tool screens for. This tool does not assess wounds. Keep the "
            "area clean, and see a doctor if it does not heal, or if it becomes painful, "
            "swollen, hot, or shows signs of infection."
        ),
        Language.HINDI: (
            "यह इस उपकरण द्वारा जाँची जाने वाली स्थितियों के बजाय एक घाव, खरोंच, चोट या अन्य त्वचा "
            "क्षति जैसा दिखता है। यह उपकरण घावों का आकलन नहीं करता। उस हिस्से को साफ़ रखें, और यदि "
            "यह ठीक न हो, या इसमें दर्द, सूजन, गर्माहट हो या संक्रमण के लक्षण दिखें तो डॉक्टर से मिलें।"
        ),
    },
}


def get_disclaimer(language: Language = Language.ENGLISH) -> str:
    return DISCLAIMERS.get(language, DISCLAIMERS[Language.ENGLISH])


def outcome_name(outcome: Outcome, language: Language = Language.ENGLISH) -> str:
    return OUTCOME_NAMES[outcome].get(language, OUTCOME_NAMES[outcome][Language.ENGLISH])


def outcome_advice(outcome: Outcome, language: Language = Language.ENGLISH) -> str:
    return OUTCOME_ADVICE[outcome].get(language, OUTCOME_ADVICE[outcome][Language.ENGLISH])


def triage_label(category: TriageCategory, language: Language = Language.ENGLISH) -> str:
    return TRIAGE_LABELS[category].get(language, TRIAGE_LABELS[category][Language.ENGLISH])


def triage_advice(category: TriageCategory, language: Language = Language.ENGLISH) -> str:
    return TRIAGE_ADVICE[category].get(language, TRIAGE_ADVICE[category][Language.ENGLISH])


def confidence_phrasing(
    confidence: float, class_name: str, language: Language = Language.ENGLISH
) -> str:
    template = CONFIDENCE_PHRASING.get(language, CONFIDENCE_PHRASING[Language.ENGLISH])
    return template.format(percent=round(confidence * 100), name=class_name)


def low_confidence_notice(language: Language = Language.ENGLISH) -> str:
    return LOW_CONFIDENCE_NOTICE.get(language, LOW_CONFIDENCE_NOTICE[Language.ENGLISH])


def quality_rejection_message(language: Language = Language.ENGLISH) -> str:
    return QUALITY_REJECTION.get(language, QUALITY_REJECTION[Language.ENGLISH])


def llm_unavailable_notice(language: Language = Language.ENGLISH) -> str:
    return LLM_UNAVAILABLE_NOTICE.get(language, LLM_UNAVAILABLE_NOTICE[Language.ENGLISH])


RULE_REASONS: dict[str, dict[Language, str]] = {
    "flag_bleeding": {
        Language.ENGLISH: "You reported that the lesion has bled on its own.",
        Language.HINDI: "आपने बताया कि घाव से अपने आप खून बह चुका है।",
    },
    "flag_growing": {
        Language.ENGLISH: "You reported that the lesion is growing.",
        Language.HINDI: "आपने बताया कि घाव का आकार बढ़ रहा है।",
    },
    "flag_colour": {
        Language.ENGLISH: "You reported a change in the lesion's colour.",
        Language.HINDI: "आपने बताया कि घाव के रंग में बदलाव आया है।",
    },
    "flag_recent_change": {
        Language.ENGLISH: "You reported a recent change in the lesion.",
        Language.HINDI: "आपने बताया कि हाल ही में घाव में बदलाव हुआ है।",
    },
    "flag_pain": {
        Language.ENGLISH: "You reported that the lesion is painful or tender.",
        Language.HINDI: "आपने बताया कि घाव में दर्द या छूने पर तकलीफ़ होती है।",
    },
    "flag_longstanding_change": {
        Language.ENGLISH: "You reported a long-standing lesion that has recently changed.",
        Language.HINDI: "आपने बताया कि पुराना घाव हाल ही में बदलने लगा है।",
    },
    "R1_malignant_class": {
        Language.ENGLISH: "The screening model's leading category is one that can be cancerous.",
        Language.HINDI: "स्क्रीनिंग मॉडल की प्रमुख श्रेणी संभावित रूप से कैंसरयुक्त हो सकती है।",
    },
    "R2_premalignant_class": {
        Language.ENGLISH: "The screening model's leading category is one that can develop into cancer if untreated.",
        Language.HINDI: "मॉडल की प्रमुख श्रेणी अनुपचारित रहने पर कैंसर में बदल सकती है।",
    },
    "R3_malignant_mass_high": {
        Language.ENGLISH: "A substantial part of the model's output pointed toward categories that can be cancerous.",
        Language.HINDI: "मॉडल के परिणामों का एक बड़ा हिस्सा संभावित कैंसरयुक्त श्रेणियों की ओर संकेत करता है।",
    },
    "R4_malignant_mass_moderate": {
        Language.ENGLISH: "Part of the model's output pointed toward categories that can be cancerous.",
        Language.HINDI: "मॉडल के परिणामों का कुछ हिस्सा संभावित कैंसरयुक्त श्रेणियों की ओर संकेत करता है।",
    },
    "R4b_premalignant_mass": {
        Language.ENGLISH: "Part of the model's output pointed toward a category that can develop into cancer if left untreated.",
        Language.HINDI: "मॉडल का कुछ परिणाम ऐसी श्रेणी की ओर संकेत करता है जो अनुपचारित रहने पर कैंसर बन सकती है।",
    },
    "R5_low_confidence": {
        Language.ENGLISH: "The model was not confident about this image, so this result should be checked by a professional rather than relied upon.",
        Language.HINDI: "मॉडल इस तस्वीर को लेकर आश्वस्त नहीं था, इसलिए इस पर निर्भर रहने के बजाय विशेषज्ञ से जाँच कराएँ।",
    },
    "R6_multiple_red_flags": {
        Language.ENGLISH: "You reported {count} symptoms that warrant prompt attention.",
        Language.HINDI: "आपने {count} ऐसे लक्षणों की जानकारी दी है जिन पर तत्काल ध्यान देने की आवश्यकता है।",
    },
    "R7_red_flag": {
        Language.ENGLISH: "You reported at least one symptom that warrants professional attention.",
        Language.HINDI: "आपने कम से कम एक ऐसा लक्षण बताया है जिसके लिए पेशेवर जाँच की ज़रूरत है।",
    },
    "R8_bleeding": {
        Language.ENGLISH: "A lesion that bleeds without being injured should be examined promptly.",
        Language.HINDI: "बिना चोट लगे जिस घाव से खून आए, उसकी तुरंत पेशेवर जाँच होनी चाहिए।",
    },
    "R9_default_routine": {
        Language.ENGLISH: "Nothing in the image analysis or your answers indicated urgency. This is a screening result only, not a clearance.",
        Language.HINDI: "तस्वीर या आपके उत्तरों में कोई तात्कालिक चिंता नहीं पाई गई। यह केवल स्क्रीनिंग है, चिकित्सकीय प्रमाणन नहीं।",
    },
}


def triage_reason(rule_id: str, default_text: str = "", language: Language = Language.ENGLISH, count: int | None = None) -> str:
    """Return localized text for a triage rule reason."""
    rule_dict = RULE_REASONS.get(rule_id)
    if not rule_dict:
        return default_text
    text = rule_dict.get(language, rule_dict.get(Language.ENGLISH, default_text))
    if count is not None and "{count}" in text:
        return text.format(count=count)
    return text
